name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: sumClassifier
      id: sumclassifier
      uses: education/autograding-command-grader@v1
      with:
        test-name: sumClassifier
        setup-command: npm install
        command: npm test sumClassifier.test.js
        timeout: 10
        max-score: 25
    - name: filterWords
      id: filterwords
      uses: education/autograding-command-grader@v1
      with:
        test-name: filterWords
        setup-command: npm install
        command: npm test filterWords
        timeout: 10
        max-score: 25
    - name: sumOfEven
      id: sumofeven
      uses: education/autograding-command-grader@v1
      with:
        test-name: sumOfEven
        setup-command: npm install
        command: npm test sumOfEven.test.js
        timeout: 10
        max-score: 25
    - name: sumOfSquares
      id: sumofsquares
      uses: education/autograding-command-grader@v1
      with:
        test-name: sumOfSquares
        setup-command: npm install
        command: npm test sumOfSquares.test.js
        timeout: 10
        max-score: 25
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        SUMCLASSIFIER_RESULTS: "${{steps.sumclassifier.outputs.result}}"
        FILTERWORDS_RESULTS: "${{steps.filterwords.outputs.result}}"
        SUMOFEVEN_RESULTS: "${{steps.sumofeven.outputs.result}}"
        SUMOFSQUARES_RESULTS: "${{steps.sumofsquares.outputs.result}}"
      with:
        runners: sumclassifier,filterwords,sumofeven,sumofsquares
